### ISSUE TITLE
Check coverage for a collection of fields

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#35]
From https://github.com/open-contracting/kingfisher-summarize/issues/29#issuecomment-733425869:

> we should look at how we can auto-generate queries with the correct joins to check coverage for a collection of fields, after which we can ask Camila to update the usability checks notebook she shared in CRM issue 5084.

There's an example of the type of query I'm thinking of in: https://github.com/open-contracting/kingfisher-summarize/issues/29#issuecomment-680326386, though that may change depending on how the issue is resolved.

Ideally we'd have a `get_coverage` method which accepts a list of field paths as a parameter and returns the % of (compiled) releases in which the collection of fields is present.

I need to think through what the input and output should be when you want to measure coverage at a level other than release, e.g. awards, contracts etc.

**Comment by duncandewhurst** [comment]
> I need to think through what the input and output should be when you want to measure coverage at a level other than release, e.g. awards, contracts etc.

My notes on this are in this notebook: https://colab.research.google.com/drive/1h9IZLqS1w9GxP-5Nk2IbibE47syhxFax#scrollTo=gw9NJGvlZiWW

**Comment by duncandewhurst** [comment]
Sharing OCP's list of [indicators mapped to OCDS](https://docs.google.com/spreadsheets/d/1j-Y0ktZiOyhZzi-2GSabBCnzx6fF5lv8h1KYwi_Q9GM/edit#gid=1075539355) and [red flags mapped to OCDS](https://docs.google.com/spreadsheets/d/12PFkUlQH09jQvcnORjcbh9-8d-NnIuk4mAQwdGiXeSM/edit#gid=0), which can serve to identify test cases and edge cases.

**Comment by Bjwebb** [comment]
I had a look at whether the SQL/JSON Path Language would help us with this, and I don't think it does. The queries @duncandewhurst has written in the notebook loook to be the most sensible way of querying this. They rely on field_list though, which increases the time to run kingfisher summarize quite a lot. From the spreadsheets of indicators / red flags, it looks like we want to run a lot queries like this, so the time up front on field_list is probably worth it.

I've implemented this for the single table case in https://colab.research.google.com/drive/1NoQMcN42UEF-NSUTD-ogjDETXBqF4REa. It reproduces the same results as the manual examples.

Next week I'll look at extending this to multiple tables.

**Comment by duncandewhurst** [comment]
Thanks, @Bjwebb.

> From the spreadsheets of indicators / red flags, it looks like we want to run a lot queries like this, so the time up front on field_list is probably worth it.

Yep - that's my thinking.

**Comment by Bjwebb** [comment]
@duncandewhurst When you say:

> However, calculating the proportion of awards with a value less than the contract requires the same fields, but you need to know how many `Award` objects have the required fields **and** have a related `Contract` object with the required fields.

Do you mean:
* have related `Contract` objects, any of which have the required fields
* have related `Contract` objects, all of which have the required fields

And, is this the same if `contract_award_join=False`?

**Comment by duncandewhurst** [comment]
Ah, good spot and good question. I think the best option might depend on the indicator. In this case, there are downsides to either option. If you measure coverage based on **any** related contract having the required fields, then you might overestimate the coverage if an award has two related contracts both of which are active but only one of which has a value. If you measure coverage based on **all** related contracts having the required fields, then you might underestimate the coverage an award has an active contract with a value and a cancelled contract without a value. Then again, you might want to include the value of cancelled contracts in your calculation, in which case the coverage would be correct, so I suppose it depends on the analyst too. 

It seems like a bit of an edge case and whatever we do will be more accurate than the current approach to measure coverage, so let's go with the latter option (**all**) and make sure to document it.

> And, is this the same if contract_award_join=False?

As above, let's go with **all** and document it.

> (from IRC) could you recommend a dataset that has multiple contracts per award?

costa_rica_poder_judicial_releases (collection 2111)

**Comment by jpmckinney** [comment]
What magnitude difference do we find between simple coverage (individual fields) vs co-occurrence coverage? I know it’s theoretically possible for two fields each with 50% simple coverage to have 0% co-occurrence, but with real data, is it more like 46% (<10% error) or more like 35% (significant error)? cc @yolile and @camilamila since you’ve run similar queries.

**Comment by yolile** [comment]
I will let @Camilamila tell you about her experience in calculating coverage for indicators. However, I think that at least for the award->contracts relationship and at least in my experience is relatively infrequently to find an award with multiple contracts

**Comment by duncandewhurst** [comment]
In uk_fts, `tender.value.amount` has 35% simple coverage and `contracts.value.amount` has 38% simple coverage (per contracting process) whilst the co-occurrence coverage of the two fields per contracting process is <1%.

I can look for more examples, if needed.

**Comment by jpmckinney** [comment]
Interesting... In the EU profile, the only way `contracts.value.amount` can be set but not `tender.value.amount` is if it's a Contract Award Notice with no prior Contract Notice or PIN. This can occur in a framework agreement and in voluntary disclosures. The only way a `tender.value.amount` can be set but not `contracts.value.amount` is if it's a PIN or if the procedure is unsuccessful. In short, I'm not sure what's going on in the UK.

**Comment by Camilamila** [comment]
I haven't calculated how frequent  these cases are, but for some publishers for instance the UK there were cases were there was no co-occurrence for example with tenderPeriod/startDate and awards/date.  From the recent usability notebooks I've run (Kyrgyz, Edo state) I haven't encountered such cases

**Comment by duncandewhurst** [comment]
Yep, we've reported this issue (tender and award notices being published under different OCIDs) to the publisher several times. It's a problem for both Contracts Finder and FTS. I've followed up again in CRM-7756.

I found some non-UK examples too:

* In australia_nsw,  `tender.value.amount` has 5% simple coverage and `awards.value.amount` has 31% simple coverage (per contracting process) whilst the co-occurrence coverage of the two fields per contracting process is <1%.
* In chile_compra_bulk,  `tender.value.amount` has 55% simple coverage and `awards.value.amount` has 79% simple coverage (per contracting process) whilst the co-occurrence coverage of the two fields per contracting process is 44%.
* In honduras_portal_bulk,  `tender.tenderPeriod.endDate` has 28% simple coverage and `contracts.period.startDate` has 20% simple coverage (per contracting process) whilst the co-occurrence coverage of the two fields per contracting process is <1%.

These were just some likely candidates I found by quickly scanning the coverage stats in the OCDS Downloads interface. There are probably others depending on the groups of fields required for different indicators.

**Comment by jpmckinney** [comment]
Thanks! Large magnitudes seem to suggest either a major data quality issue (like in the UK), or some special distribution of contracting data (e.g. a large number of PINs and call-offs).

For example, Honduras seems like it has a quality issue.

Chile seems okay: the maximum possible co-occurrence is 55%, and 44% is within 25% of that (55/44) – there are probably good reasons for the difference (not-yet-awarded or unsuccessful procedures, etc.).

I'm not too worried about the co-occurrence in Australia, since 5% is low for simple coverage. That said, they seem to really not have many values, which is concerning (do they mostly only published contracts.value.amount?).

**Comment by duncandewhurst** [comment]
Yep, I agree with your reasoning and I think that these issues/unusual distributions demonstrate that it's useful to look at co-occurrence as well as simple coverage.

> I'm not too worried about the co-occurrence in Australia, since 5% is low for simple coverage. That said, they seem to really not have many values, which is concerning (do they mostly only published contracts.value.amount?).

They don't publish the `contracts` at all (you can see the full coverage stats here: https://ocds-downloads.opendata.coop/source/australia_nsw). It [looks like](https://www.tenders.nsw.gov.au/?event=public.RFT.list) the system on which the OCDS implementation is based doesn't capture tender values, I don't remember why. I'm not sure why 5% of tenders have values, perhaps from planning notices. Similar to the UK, there is also an issue in the source system (not just in the OCDS implementation) with linking awards and tenders.

**Comment by kindly** [comment]
After many different attempts at trying to do this (in a somewhat clean way) I have settled on the an approach as the best option but would like to run in past @jpmckinney before I go into implementing it fully.

Firstly the main difficulty with the above is the **all** condition on one-to-many relationships. The **any** case is not  problematic as is mostly covered by the current `field_list` fields.

For example if you are looking at `awards` and want to count coverage passing if **all** `award.suppliers` have an `address`. Currently in order to do this query you will need to look into the `award_suppliers_summary` table and group by the `id` and `awards_index` and do a `bool_and` aggregate on the `fields_list` field in that table.
Here is some example SQL (may not be entirely correct) to show that.

```sql
SELECT all_have_address
FROM awards_summary
LEFT JOIN (
    SELECT id, award_index, bool_and(award_suppliers_summary.field_list ? 'address') AS has_address
    FROM award_suppliers_summary
    GROUP BY id, awardid
    ) award_suppliers_summary
USING (id, award_index)
```

A new `LEFT JOIN` like the above will have to be done on every **all** coverage field specified.  For example if you are now looking at `award.documents` and want to know that the `award.documents` have a `title`, or (for a more compicated case) if you want to know that all `tenderers` that are in that contracting process also have an `address`.

After looking at generating the SQL for the above, it seemed very difficult and hard to maintain.  It is tricky to work out from the input what `summary` tables to join on (and work out the join condition) and I worry about the performance implications of doing a subquery with a GROUP BY for each **all** condition because if the tables are large then each sub query most likely will be made into a temporary table by PostgreSQL internally.   I am also concerned about the complexity/maintaiablitly of the resulting code too.

So even though the above approach is possible I do not think it is the best option.

After talking this through with @duncandewhurst and @Bjwebb the following is my preferred approach:

This is to alter kingfisher-summarize `field_list` information so they have counts of the occurence of each field not just `null` against each field.   Here is the change to summarize to do this. https://github.com/open-contracting/kingfisher-summarize/commit/bb0ce671f014b9345d539a08819c7929c5d32cc7.

So this will transform the current `field_list` fields that look like:
```
 {
     "id": null,
     "date": null,
     "title": null,
     "suppliers": null,
     "suppliers/address": null
 }
```
to look like:
```
 {
     "id": 1
     "date": 1,
     "title": 1,
     "suppliers": 2,
     "suppliers/address": 2
 }
```
This makes the above example much simplier to write as all you need to do is check if the count of `suppliers` is the same as the count of `suppliers/address`:

```sql
SELECT field_list ->> 'suppliers' =  field_list ->> 'suppliers/address'  all_have_address FROM awards_summary
```

The big **downside** of doing this is that generating the `fields_lists` tables will take even longer.  However, if the end task is likely to be generating lots of coverage metrics for indicators, then this cost upfront, is likely to pay off as the resulting queries being much faster.  It would obviously be possible to have the `counts` version of the `field_list` field an additional option, but as the `field_list` fields are optional already and as the main purpose of them is generating coverage statistics then this extra information is most likely best as the only behaviour.

As an upside all current queries using the field_list fields will continue to work as normal as they are only inspecting the keys of the JSONB anyway.

An additional *special* case that should be covered is to have the `award_summary.field_list` contain information about `contracts` so that contracts can be treated as just a normal one-to-many like the above.  So it will be trivial to ask for example if a for an `award` that **all** `contracts` related to it have a `value`.  Also vice versa the associated `award` coverage information could be added to the `contract_summary.field_list`.

Using the above fields the final function in the notebook would be somthing like:

```python 
calculate_coverage(
  [ 'title',                           
    'ALL suppliers/address',  # the special ALL field means you care about all addresses for the supplier, ANY will be default
    'ALL contracts/amount',  # ALL associated contracts have amounts
    'ALL /tender/tenderers/address' # ALL tenderers have an address. `/` at start to say you want to look at contracting process related to this award.
    ], 
    scope='awards' # the scope of where you want the coverage to be calculted.
) 
```

**Comment by duncandewhurst** [comment]
Thanks, @kindly. All sounds good to me, as we discussed.

**Comment by jpmckinney** [comment]
Sounds reasonable! For reference, how much slower is https://github.com/open-contracting/kingfisher-summarize/commit/bb0ce671f014b9345d539a08819c7929c5d32cc7 on some sample collection?

Viz "any" vs. "all", as Duncan wrote in https://github.com/open-contracting/kingfisher-colab/issues/35#issuecomment-983250704 I think it depends on the question, but I agree "all" is better in most cases.

For example, some procedures might have an unsuccessful award along with a successful award, such that an "all" query for `suppliers` will under-report coverage. However, such procedures are expected to be the exception, so it will not be a major under-reporting. Meanwhile, if the data has a quality issue (which is more likely), then an "any" query would over-report coverage (potentially producing a false negative for whatever threshold we use for identifying quality issues).

I think "any" would be better if we were doing coverage of *values* as opposed to *fields* (how many procedures set a "buyer" role, etc.), but that's not the issue here.

**Comment by kindly** [comment]
@jpmckinney 

> For reference, how much slower is [open-contracting/kingfisher-summarize@bb0ce67](https://github.com/open-contracting/kingfisher-summarize/commit/bb0ce671f014b9345d539a08819c7929c5d32cc7) on some sample collection?

It was about twice as long on a small source `zambia` but it is hard to tell how that scales with slightly bigger ones.

**Comment by jpmckinney** [comment]
Okay, not too bad – I agree that ~2x slower build time is fine considering the savings at query time.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/kingfisher-colab/pull/55
