### ISSUE TITLE
render_json: add function to render collapsible JSON in a notebook

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-colab#40]
function:

```
import json
from IPython.display import HTML

def render_json(jstr):
  if type(jstr) != str:
    jstr = json.dumps(jstr)
  return HTML("""
<script src="https://rawgit.com/caldwell/renderjson/master/renderjson.js"></script>
<script>
renderjson.set_show_to_level(1)
document.body.appendChild(renderjson(%s))
new ResizeObserver(google.colab.output.resizeIframeToContent).observe(document.body)
</script>
""" % jstr)
```

usage:

```
render_json("""{"example_array": [1,2,3], "example_object": {"a": 1, "b":2}}""")

⊖{
    "example_array": ⊕[3 items],
    "example_object": ⊕{2 items}
}
```

**Comment by jpmckinney** [comment]
Happy for you to create a PR. Just use readable variables like `json_string` not `jstr`. We typically do `not isinstance(json_string, str)` instead of `type(jstr) != str`, and use f-strings instead of `%` substitution: https://ocp-software-handbook.readthedocs.io/en/latest/python/code.html#string-formatting

**Comment by jpmckinney** [comment]
Once this is added, update setup_environment.ipynb in https://github.com/open-contracting/kingfisher_notebook_components

**Comment by duncandewhurst** [comment]
> Once this is added, update setup_environment.ipynb in https://github.com/open-contracting/kingfisher_notebook_components

I've done this.
