### ISSUE TITLE
Consider using Spoonbill instead of Flatten Tool

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-colab#48]

**Comment by duncandewhurst** [comment]
I'm assuming this is a placeholder issue and shouldn't be considered for sprint beginning in July. Let me know if not.

**Comment by jpmckinney** [comment]
Yes, it is just a placeholder/discussion issue for later.

**Comment by duncandewhurst** [comment]
I think the only method that uses Flatten Tool is https://kingfisher-colab.readthedocs.io/en/latest/#ocdskingfishercolab.save_dataframe_to_spreadsheet.

In the helpdesk notebook templates, that method is used [for one purpose](https://colab.research.google.com/github/open-contracting/kingfisher_notebook_components/blob/main/check_data_quality.ipynb#scrollTo=YyL6ruuNRTA0&line=1&uniqifier=1): to help analysts check for differences between releases from the same contracting process, in order to check whether the publisher has implemented releases and records correctly. For that use case, I don't think Spoonbill offers any advantages over Flatten Tool.

I expect other use cases around accessing flattened data to be served by the launch of registry so I don't think this is too high of a priority for now.
